// constants/errorCodes.ts
// v7.14 FIX-V714-6: Canonical error constants
// v7.24 FIX-V724-5: 36 total error codes including 8 new security codes
// G65 LINT ALLOWLIST: add 'constants/errorCodes' to the no-restricted-imports exceptions.

export const ERR = {
  LEASE_HELD: 'LEASE_HELD',
  SAFE_MODE_ACTIVE: 'SAFE_MODE_ACTIVE',
  MAX_FIRMS_REACHED: 'MAX_FIRMS_REACHED',
  FIRM_CODE_IMMUTABLE: 'FIRM_CODE_IMMUTABLE',
  GSTIN_IMMUTABLE: 'GSTIN_IMMUTABLE',
  GSTIN_STATE_MISMATCH: 'GSTIN_STATE_MISMATCH',
  GSTIN_STATE_UPDATE_BLOCKED: 'GSTIN_STATE_UPDATE_BLOCKED',
  FIRM_NOT_FOUND: 'FIRM_NOT_FOUND',
  CANNOT_ARCHIVE_ACTIVE_FIRM: 'CANNOT_ARCHIVE_ACTIVE_FIRM',
  LAST_FIRM: 'LAST_FIRM',
  AUDIT_LOG_IMMUTABLE: 'AUDIT_LOG_IMMUTABLE',
  RESTORE_VALIDATION_FAILED: 'RESTORE_VALIDATION_FAILED',
  RESTORE_OLD_SCHEMA: 'RESTORE_OLD_SCHEMA',
  STORAGE_CORRUPTION_DETECTED: 'STORAGE_CORRUPTION_DETECTED',
  FY_INTEGRITY_BROKEN: 'FY_INTEGRITY_BROKEN',
  SCHEMA_VERSION_MISMATCH: 'SCHEMA_VERSION_MISMATCH',
  AMOUNT_NOT_INTEGER: 'AMOUNT_NOT_INTEGER',
  AMOUNT_NEGATIVE: 'AMOUNT_NEGATIVE',
  AMOUNT_TOO_LARGE: 'AMOUNT_TOO_LARGE',
  INVALID_GSTIN: 'INVALID_GSTIN',
  INVALID_PINCODE: 'INVALID_PINCODE',
  INVALID_FIRM_CODE: 'INVALID_FIRM_CODE',
  WRITE_LEASE_NOT_IMPLEMENTED: 'WRITE_LEASE_NOT_IMPLEMENTED',
  BOOTSTRAP_INCOMPLETE: 'BOOTSTRAP_INCOMPLETE',
  ENTRY_DATE_IN_CLOSED_FY: 'ENTRY_DATE_IN_CLOSED_FY',
  CHECKSUM_MISMATCH: 'CHECKSUM_MISMATCH',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  DEVICE_ID_NOT_INITIALIZED: 'DEVICE_ID_NOT_INITIALIZED',
  // v7.23 FIX-VSEC-1: backup encryption
  BACKUP_PASSWORD_REQUIRED: 'BACKUP_PASSWORD_REQUIRED',
  // v7.23 FIX-VSEC-2: MMKV cache tamper detection
  MMKV_CACHE_TAMPERED: 'MMKV_CACHE_TAMPERED',
  // v7.23 FIX-VSEC-3: PIN gate
  PIN_INCORRECT: 'PIN_INCORRECT',
  PIN_LOCKED: 'PIN_LOCKED',
  PIN_DATA_CORRUPTED: 'PIN_DATA_CORRUPTED',
  // v7.23 FIX-VSEC-7: input sanitization
  INVALID_TEXT_CONTENT: 'INVALID_TEXT_CONTENT',
  // v7.23 FIX-VSEC-8: device ID audit chain
  DEVICE_ID_CHANGED: 'DEVICE_ID_CHANGED',
  // v7.23 FIX-VSEC-11: checksum envelope coverage
  CHECKSUM_ENVELOPE_MISMATCH: 'CHECKSUM_ENVELOPE_MISMATCH',
  // v7.23 FIX-VSEC-12: factory reset
  FACTORY_RESET_EXECUTED: 'FACTORY_RESET_EXECUTED',
  // --- Phase 2 Error Codes (STEP EC) ---
  
  // Firm ownership guards
  FIRM_ID_AND_CATEGORY_ID_REQUIRED: 'FIRM_ID_AND_CATEGORY_ID_REQUIRED',
  FIRM_ID_AND_DESIGN_ID_REQUIRED: 'FIRM_ID_AND_DESIGN_ID_REQUIRED',
  FIRM_ID_AND_ITEM_ID_REQUIRED: 'FIRM_ID_AND_ITEM_ID_REQUIRED',
  FIRM_ID_REQUIRED: 'FIRM_ID_REQUIRED',
  
  // Category
  CATEGORY_NOT_FOUND_OR_WRONG_FIRM: 'CATEGORY_NOT_FOUND_OR_WRONG_FIRM',
  CATEGORY_HAS_ACTIVE_ITEMS: 'CATEGORY_HAS_ACTIVE_ITEMS', 
  CATEGORY_NAME_DUPLICATE: 'CATEGORY_NAME_DUPLICATE',
  CATEGORY_CODE_GENERATION_FAILED: 'CATEGORY_CODE_GENERATION_FAILED',
  
  // Design
  DESIGN_NOT_FOUND_OR_WRONG_FIRM: 'DESIGN_NOT_FOUND_OR_WRONG_FIRM', 
  DESIGN_HAS_ACTIVE_ITEMS: 'DESIGN_HAS_ACTIVE_ITEMS', 
  DESIGN_NAME_INVALID: 'DESIGN_NAME_INVALID',
  DESIGN_NAME_TAKEN: 'DESIGN_NAME_TAKEN',
  DESIGN_CODE_GENERATION_FAILED: 'DESIGN_CODE_GENERATION_FAILED',
  DESIGN_LOW_STOCK_THRESHOLD_INVALID: 'DESIGN_LOW_STOCK_THRESHOLD_INVALID',
  
  // Stone / Gemstone
  STONE_NOT_FOUND_OR_WRONG_FIRM: 'STONE_NOT_FOUND_OR_WRONG_FIRM', 
  GEMSTONE_WEIGHT_INVALID: 'GEMSTONE_WEIGHT_INVALID', 
  GEMSTONE_QUANTITY_INVALID: 'GEMSTONE_QUANTITY_INVALID',
  GEMSTONE_LOT_NOT_FOUND_OR_WRONG_FIRM: 'GEMSTONE_LOT_NOT_FOUND_OR_WRONG_FIRM', 
  INVALID_GEMSTONE_TRANSITION: 'INVALID_GEMSTONE_TRANSITION',
  
  // HSN / SKU
  ITEM_HSN_MISSING: 'ITEM_HSN_MISSING', 
  SKU_GENERATION_FAILED: 'SKU_GENERATION_FAILED',
  
  // Item core
  ITEM_NOT_FOUND_OR_WRONG_FIRM: 'ITEM_NOT_FOUND_OR_WRONG_FIRM', 
  ITEM_GROSS_WEIGHT_INVALID: 'ITEM_GROSS_WEIGHT_INVALID', 
  ITEM_PURITY_PERCENT_INVALID: 'ITEM_PURITY_PERCENT_INVALID',
  ITEM_NET_WEIGHT_INVALID: 'ITEM_NET_WEIGHT_INVALID', 
  ITEM_NOT_AVAILABLE: 'ITEM_NOT_AVAILABLE', 
  ITEM_ALREADY_SOLD: 'ITEM_ALREADY_SOLD', 
  ITEM_NOT_DRAFT: 'ITEM_NOT_DRAFT',
  ITEM_DELETE_LOCKED_TERMINAL_STATUS: 'ITEM_DELETE_LOCKED_TERMINAL_STATUS', 
  ITEM_ACTION_REASON_REQUIRED: 'ITEM_ACTION_REASON_REQUIRED',
  INVALID_TRANSITION: 'INVALID_TRANSITION', 
  INVALID_KARAT: 'INVALID_KARAT', 
  WEIGHT_EDIT_AFTER_DRAFT_FORBIDDEN: 'WEIGHT_EDIT_AFTER_DRAFT_FORBIDDEN', 
  ITEM_EDIT_LOCKED_TERMINAL_STATUS: 'ITEM_EDIT_LOCKED_TERMINAL_STATUS', 
  ITEM_SIZE_PAIRING_INVALID: 'ITEM_SIZE_PAIRING_INVALID',
  BULK_ITEM_MAX_EXCEEDED: 'BULK_ITEM_MAX_EXCEEDED', 
  KARIGAR_LOOP_LIMIT_EXCEEDED: 'KARIGAR_LOOP_LIMIT_EXCEEDED',
  
  // Phantom inventory
  PHANTOM_ITEM_NOT_FOUND: 'PHANTOM_ITEM_NOT_FOUND', 
  PHANTOM_ITEM_ALREADY_SOLD: 'PHANTOM_ITEM_ALREADY_SOLD',
  PHANTOM_NOT_YET_SOLD: 'PHANTOM_NOT_YET_SOLD', 
  PHANTOM_ALREADY_RECONCILED: 'PHANTOM_ALREADY_RECONCILED',
  REAL_ITEM_NOT_FOUND: 'REAL_ITEM_NOT_FOUND', 
  REAL_ITEM_NOT_AVAILABLE_FOR_RECONCILE: 'REAL_ITEM_NOT_AVAILABLE_FOR_RECONCILE',
  REAL_ITEM_ALREADY_USED_FOR_RECONCILE: 'REAL_ITEM_ALREADY_USED_FOR_RECONCILE',
  RECONCILE_DESIGN_MISMATCH: 'RECONCILE_DESIGN_MISMATCH', 
  RECONCILE_WEIGHT_MISMATCH: 'RECONCILE_WEIGHT_MISMATCH', 
  RECONCILE_PURITY_MISMATCH: 'RECONCILE_PURITY_MISMATCH',
  STALE_PHANTOM_ITEMS: 'STALE_PHANTOM_ITEMS',
  
  // FY
  FY_OWNERSHIP_MISMATCH: 'FY_OWNERSHIP_MISMATCH', 
  FY_NOT_ACTIVE: 'FY_NOT_ACTIVE', 
  FY_CLOSE_BLOCKED_DRAFT_ITEMS: 'FY_CLOSE_BLOCKED_DRAFT_ITEMS',
  FY_CLOSE_BLOCKED_CRITICAL_VERIFY: 'FY_CLOSE_BLOCKED_CRITICAL_VERIFY',
  FY_CLOSE_BLOCKED_PHANTOM_ITEMS: 'FY_CLOSE_BLOCKED_PHANTOM_ITEMS',
  ENTRY_DATE_IN_FUTURE: 'ENTRY_DATE_IN_FUTURE', 
  FY_NOT_FOUND: 'FY_NOT_FOUND',
  
  // Old gold / URD
  OLD_GOLD_PURITY_PERCENT_INVALID: 'OLD_GOLD_PURITY_PERCENT_INVALID', 
  OLD_GOLD_GROSS_WEIGHT_INVALID: 'OLD_GOLD_GROSS_WEIGHT_INVALID',
  OLD_GOLD_LOT_NOT_FOUND_OR_WRONG_FIRM: 'OLD_GOLD_LOT_NOT_FOUND_OR_WRONG_FIRM',
  INVALID_LOT_TRANSITION: 'INVALID_LOT_TRANSITION', 
  ISSUED_TO_KARIGAR_REQUIRES_MELT_OUTPUT: 'ISSUED_TO_KARIGAR_REQUIRES_MELT_OUTPUT',
  URD_NOT_FOUND_OR_WRONG_FIRM: 'URD_NOT_FOUND_OR_WRONG_FIRM', 
  URD_ALREADY_CONFIRMED: 'URD_ALREADY_CONFIRMED', 
  URD_NOT_CONFIRMED: 'URD_NOT_CONFIRMED',
  URD_CUSTOMER_NAME_REQUIRED: 'URD_CUSTOMER_NAME_REQUIRED',
  URD_GROSS_WEIGHT_INVALID: 'URD_GROSS_WEIGHT_INVALID', 
  URD_PURITY_PERCENT_INVALID: 'URD_PURITY_PERCENT_INVALID', 
  URD_RATE_INVALID: 'URD_RATE_INVALID',
  URD_BANK_ACCOUNT_REQUIRED: 'URD_BANK_ACCOUNT_REQUIRED', 
  URD_BANK_ACCOUNT_MUST_BE_NULL_FOR_CASH: 'URD_BANK_ACCOUNT_MUST_BE_NULL_FOR_CASH', 
  URD_AMOUNT_EXCEEDS_MAX: 'URD_AMOUNT_EXCEEDS_MAX',
  
  // HUID
  HUID_INVALID: 'HUID_INVALID', 
  HUID_ALREADY_EXISTS: 'HUID_ALREADY_EXISTS', 
  HUID_ALREADY_SET: 'HUID_ALREADY_SET', 
  HUID_NOT_SET: 'HUID_NOT_SET'
} as const;