// constants/errorCodes.ts
// Canonical error constants strictly aligned with VJ BILLING Phase 2 v2.34
// Implements FIX-OLDMETAL-RENAME-1 (v2.32), FIX-STEPEC-RESTATE-RETRACT-1 (v2.30)

export const ERR = {
  // --- Phase 1 Core Error Codes (37 entries) ---
  LEASE_HELD: 'LEASE_HELD',
  SAFE_MODE_ACTIVE: 'SAFE_MODE_ACTIVE',
  MAX_FIRMS_REACHED: 'MAX_FIRMS_REACHED',
  FIRM_CODE_IMMUTABLE: 'FIRM_CODE_IMMUTABLE',
  GSTIN_ALREADY_SET: 'GSTIN_ALREADY_SET', // v7.35 FIX-V735-1: renamed from GSTIN_IMMUTABLE
  GSTIN_STATE_MISMATCH: 'GSTIN_STATE_MISMATCH',
  GSTIN_STATE_UPDATE_BLOCKED: 'GSTIN_STATE_UPDATE_BLOCKED',
  FIRM_NOT_FOUND: 'FIRM_NOT_FOUND',
  CANNOT_ARCHIVE_ACTIVE_FIRM: 'CANNOT_ARCHIVE_ACTIVE_FIRM',
  LAST_FIRM: 'LAST_FIRM',
  AUDIT_LOG_IMMUTABLE: 'AUDIT_LOG_IMMUTABLE',
  RESTORE_VALIDATION_FAILED: 'RESTORE_VALIDATION_FAILED',
  RESTORE_OLD_SCHEMA: 'RESTORE_OLD_SCHEMA',
  STORAGE_CORRUPTION_DETECTED: 'STORAGE_CORRUPTION_DETECTED',
  FY_INTEGRITY_BROKEN: 'FY_INTEGRITY_BROKEN',
  SCHEMA_VERSION_MISMATCH: 'SCHEMA_VERSION_MISMATCH',
  AMOUNT_NOT_INTEGER: 'AMOUNT_NOT_INTEGER',
  AMOUNT_NEGATIVE: 'AMOUNT_NEGATIVE',
  AMOUNT_TOO_LARGE: 'AMOUNT_TOO_LARGE',
  INVALID_GSTIN: 'INVALID_GSTIN',
  INVALID_PINCODE: 'INVALID_PINCODE',
  INVALID_FIRM_CODE: 'INVALID_FIRM_CODE',
  WRITE_LEASE_NOT_IMPLEMENTED: 'WRITE_LEASE_NOT_IMPLEMENTED',
  BOOTSTRAP_INCOMPLETE: 'BOOTSTRAP_INCOMPLETE',
  ENTRY_DATE_IN_CLOSED_FY: 'ENTRY_DATE_IN_CLOSED_FY',
  CHECKSUM_MISMATCH: 'CHECKSUM_MISMATCH',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  DEVICE_ID_NOT_INITIALIZED: 'DEVICE_ID_NOT_INITIALIZED',
  BACKUP_PASSWORD_REQUIRED: 'BACKUP_PASSWORD_REQUIRED',
  MMKV_CACHE_TAMPERED: 'MMKV_CACHE_TAMPERED',
  PIN_INCORRECT: 'PIN_INCORRECT',
  PIN_LOCKED: 'PIN_LOCKED',
  PIN_DATA_CORRUPTED: 'PIN_DATA_CORRUPTED',
  INVALID_TEXT_CONTENT: 'INVALID_TEXT_CONTENT',
  DEVICE_ID_CHANGED: 'DEVICE_ID_CHANGED',
  CHECKSUM_ENVELOPE_MISMATCH: 'CHECKSUM_ENVELOPE_MISMATCH',
  FACTORY_RESET_EXECUTED: 'FACTORY_RESET_EXECUTED',

  // --- Phase 2 Error Codes (STEP EC) ---

  // Firm ownership guards
  FIRM_ID_AND_CATEGORY_ID_REQUIRED: 'FIRM_ID_AND_CATEGORY_ID_REQUIRED',
  FIRM_ID_AND_DESIGN_ID_REQUIRED: 'FIRM_ID_AND_DESIGN_ID_REQUIRED',
  FIRM_ID_AND_ITEM_ID_REQUIRED: 'FIRM_ID_AND_ITEM_ID_REQUIRED',
  FIRM_ID_REQUIRED: 'FIRM_ID_REQUIRED',

  // Category
  CATEGORY_NOT_FOUND_OR_WRONG_FIRM: 'CATEGORY_NOT_FOUND_OR_WRONG_FIRM',
  CATEGORY_HAS_ACTIVE_ITEMS: 'CATEGORY_HAS_ACTIVE_ITEMS',
  CATEGORY_NAME_DUPLICATE: 'CATEGORY_NAME_DUPLICATE',
  CATEGORY_CODE_GENERATION_FAILED: 'CATEGORY_CODE_GENERATION_FAILED',

  // Design
  DESIGN_NOT_FOUND_OR_WRONG_FIRM: 'DESIGN_NOT_FOUND_OR_WRONG_FIRM',
  DESIGN_HAS_ACTIVE_ITEMS: 'DESIGN_HAS_ACTIVE_ITEMS',
  DESIGN_NAME_INVALID: 'DESIGN_NAME_INVALID',
  DESIGN_NAME_TAKEN: 'DESIGN_NAME_TAKEN',
  DESIGN_CODE_GENERATION_FAILED: 'DESIGN_CODE_GENERATION_FAILED',
  DESIGN_METAL_IMMUTABLE: 'DESIGN_METAL_IMMUTABLE',
  DESIGN_PURITY_LOW_STOCK_THRESHOLD_INVALID: 'DESIGN_PURITY_LOW_STOCK_THRESHOLD_INVALID',
  DESIGN_LOW_STOCK_THRESHOLD_INVALID: 'DESIGN_PURITY_LOW_STOCK_THRESHOLD_INVALID', // Backward compatibility alias

  // Stone / Gemstone
  STONE_NOT_FOUND_OR_WRONG_FIRM: 'STONE_NOT_FOUND_OR_WRONG_FIRM',
  GEMSTONE_WEIGHT_INVALID: 'GEMSTONE_WEIGHT_INVALID',
  GEMSTONE_QUANTITY_INVALID: 'GEMSTONE_QUANTITY_INVALID',
  GEMSTONE_LOT_NOT_FOUND_OR_WRONG_FIRM: 'GEMSTONE_LOT_NOT_FOUND_OR_WRONG_FIRM',
  INVALID_GEMSTONE_TRANSITION: 'INVALID_GEMSTONE_TRANSITION',

  // HSN / SKU
  ITEM_HSN_MISSING: 'ITEM_HSN_MISSING',
  SKU_GENERATION_FAILED: 'SKU_GENERATION_FAILED',

  // Item core
  ITEM_NOT_FOUND_OR_WRONG_FIRM: 'ITEM_NOT_FOUND_OR_WRONG_FIRM',
  ITEM_GROSS_WEIGHT_INVALID: 'ITEM_GROSS_WEIGHT_INVALID',
  ITEM_PURITY_PERCENT_INVALID: 'ITEM_PURITY_PERCENT_INVALID',
  ITEM_NET_WEIGHT_INVALID: 'ITEM_NET_WEIGHT_INVALID',
  ITEM_NOT_AVAILABLE: 'ITEM_NOT_AVAILABLE',
  ITEM_ALREADY_SOLD: 'ITEM_ALREADY_SOLD',
  ITEM_NOT_DRAFT: 'ITEM_NOT_DRAFT',
  ITEM_DELETE_LOCKED_TERMINAL_STATUS: 'ITEM_DELETE_LOCKED_TERMINAL_STATUS',
  ITEM_ACTION_REASON_REQUIRED: 'ITEM_ACTION_REASON_REQUIRED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INVALID_KARAT: 'INVALID_KARAT',
  WEIGHT_EDIT_AFTER_DRAFT_FORBIDDEN: 'WEIGHT_EDIT_AFTER_DRAFT_FORBIDDEN', // DEPRECATED v1.77
  ITEM_EDIT_LOCKED_TERMINAL_STATUS: 'ITEM_EDIT_LOCKED_TERMINAL_STATUS',
  ITEM_SIZE_PAIRING_INVALID: 'ITEM_SIZE_PAIRING_INVALID',
  BULK_ITEM_MAX_EXCEEDED: 'BULK_ITEM_MAX_EXCEEDED',
  KARIGAR_LOOP_LIMIT_EXCEEDED: 'KARIGAR_LOOP_LIMIT_EXCEEDED',
  KARIGAR_NAME_REQUIRED: 'KARIGAR_NAME_REQUIRED',

  // Phantom inventory
  PHANTOM_ITEM_NOT_FOUND: 'PHANTOM_ITEM_NOT_FOUND',
  PHANTOM_ITEM_ALREADY_SOLD: 'PHANTOM_ITEM_ALREADY_SOLD',
  PHANTOM_NOT_YET_SOLD: 'PHANTOM_NOT_YET_SOLD',
  PHANTOM_ALREADY_RECONCILED: 'PHANTOM_ALREADY_RECONCILED',
  REAL_ITEM_NOT_FOUND: 'REAL_ITEM_NOT_FOUND',
  REAL_ITEM_NOT_AVAILABLE_FOR_RECONCILE: 'REAL_ITEM_NOT_AVAILABLE_FOR_RECONCILE',
  REAL_ITEM_ALREADY_USED_FOR_RECONCILE: 'REAL_ITEM_ALREADY_USED_FOR_RECONCILE',
  RECONCILE_DESIGN_MISMATCH: 'RECONCILE_DESIGN_MISMATCH',
  RECONCILE_WEIGHT_MISMATCH: 'RECONCILE_WEIGHT_MISMATCH',
  RECONCILE_PURITY_MISMATCH: 'RECONCILE_PURITY_MISMATCH',
  STALE_PHANTOM_ITEMS: 'STALE_PHANTOM_ITEMS',

  // FY
  FY_OWNERSHIP_MISMATCH: 'FY_OWNERSHIP_MISMATCH',
  FY_NOT_ACTIVE: 'FY_NOT_ACTIVE',
  FY_CLOSE_BLOCKED_DRAFT_ITEMS: 'FY_CLOSE_BLOCKED_DRAFT_ITEMS',
  FY_CLOSE_BLOCKED_CRITICAL_VERIFY: 'FY_CLOSE_BLOCKED_CRITICAL_VERIFY',
  FY_CLOSE_BLOCKED_PHANTOM_ITEMS: 'FY_CLOSE_BLOCKED_PHANTOM_ITEMS',
  ENTRY_DATE_IN_FUTURE: 'ENTRY_DATE_IN_FUTURE',
  FY_NOT_FOUND: 'FY_NOT_FOUND',

  // Old Metal / URD — v2.32 FIX-OLDMETAL-RENAME-1
  OLD_METAL_PURITY_PERCENT_INVALID: 'OLD_METAL_PURITY_PERCENT_INVALID',
  OLD_METAL_GROSS_WEIGHT_INVALID: 'OLD_METAL_GROSS_WEIGHT_INVALID',
  OLD_METAL_LOT_NOT_FOUND_OR_WRONG_FIRM: 'OLD_METAL_LOT_NOT_FOUND_OR_WRONG_FIRM',
  OLD_METAL_TYPE_INVALID: 'OLD_METAL_TYPE_INVALID',

  // Backward compatibility aliases for lot-storage error family
  OLD_GOLD_PURITY_PERCENT_INVALID: 'OLD_METAL_PURITY_PERCENT_INVALID',
  OLD_GOLD_GROSS_WEIGHT_INVALID: 'OLD_METAL_GROSS_WEIGHT_INVALID',
  OLD_GOLD_LOT_NOT_FOUND_OR_WRONG_FIRM: 'OLD_METAL_LOT_NOT_FOUND_OR_WRONG_FIRM',
  OLD_GOLD_METAL_INVALID: 'OLD_METAL_TYPE_INVALID',

  INVALID_LOT_TRANSITION: 'INVALID_LOT_TRANSITION',
  ISSUED_TO_KARIGAR_REQUIRES_MELT_OUTPUT: 'ISSUED_TO_KARIGAR_REQUIRES_MELT_OUTPUT',
  URD_NOT_FOUND_OR_WRONG_FIRM: 'URD_NOT_FOUND_OR_WRONG_FIRM',
  URD_ALREADY_CONFIRMED: 'URD_ALREADY_CONFIRMED',
  URD_NOT_CONFIRMED: 'URD_NOT_CONFIRMED',
  URD_CUSTOMER_NAME_REQUIRED: 'URD_CUSTOMER_NAME_REQUIRED',
  URD_GROSS_WEIGHT_INVALID: 'URD_GROSS_WEIGHT_INVALID',
  URD_PURITY_PERCENT_INVALID: 'URD_PURITY_PERCENT_INVALID',
  URD_RATE_INVALID: 'URD_RATE_INVALID',
  URD_BANK_ACCOUNT_REQUIRED: 'URD_BANK_ACCOUNT_REQUIRED',
  URD_BANK_ACCOUNT_MUST_BE_NULL_FOR_CASH: 'URD_BANK_ACCOUNT_MUST_BE_NULL_FOR_CASH',
  URD_AMOUNT_EXCEEDS_MAX: 'URD_AMOUNT_EXCEEDS_MAX',

  // HUID
  HUID_INVALID: 'HUID_INVALID',
  HUID_ALREADY_EXISTS: 'HUID_ALREADY_EXISTS',
  HUID_ALREADY_SET: 'HUID_ALREADY_SET',
  HUID_NOT_SET: 'HUID_NOT_SET',

  // Loose Stock (STEP 6.9 — FEAT-LOOSE-STOCK-1 v2.23 / v2.24)
  LOOSE_STOCK_DESIGN_TYPE_MISMATCH: 'LOOSE_STOCK_DESIGN_TYPE_MISMATCH',
  LOOSE_STOCK_QUANTITY_INVALID: 'LOOSE_STOCK_QUANTITY_INVALID',
  LOOSE_STOCK_WEIGHT_INVALID: 'LOOSE_STOCK_WEIGHT_INVALID',
  LOOSE_LOT_NOT_FOUND_OR_WRONG_FIRM: 'LOOSE_LOT_NOT_FOUND_OR_WRONG_FIRM',
  LOOSE_LOT_INSUFFICIENT_QUANTITY: 'LOOSE_LOT_INSUFFICIENT_QUANTITY',
  LOOSE_LOT_INSUFFICIENT_WEIGHT: 'LOOSE_LOT_INSUFFICIENT_WEIGHT',

  // --- Phase 3 Error Codes (STEP 0 / Money Truth Layer) ---
  RATE_NOT_CONFIGURED: 'RATE_NOT_CONFIGURED',
  RATE_ENGINE_INVALID_INPUT: 'RATE_ENGINE_INVALID_INPUT',
  TAX_GROUP_INVALID_COMPONENTS: 'TAX_GROUP_INVALID_COMPONENTS',
  TAX_GROUP_ASYMMETRIC_RATES: 'TAX_GROUP_ASYMMETRIC_RATES',
  TAX_RATE_IN_USE: 'TAX_RATE_IN_USE',
  TAX_GROUP_IN_USE: 'TAX_GROUP_IN_USE',
  DUPLICATE_TAX_RATE_NAME: 'DUPLICATE_TAX_RATE_NAME',
  RATE_BPS_IMMUTABLE: 'RATE_BPS_IMMUTABLE',

  // --- Phase 3 Error Code Registry (STEP E) ---
  KARIGAR_NOT_FOUND: 'KARIGAR_NOT_FOUND',
  SETTLEMENT_WEIGHT_INVALID: 'SETTLEMENT_WEIGHT_INVALID',
  SETTLEMENT_RATE_INVALID: 'SETTLEMENT_RATE_INVALID',
  LINKED_METAL_ENTRY_INVALID: 'LINKED_METAL_ENTRY_INVALID',
  SETTLEMENT_EXCEEDS_METAL_BALANCE: 'SETTLEMENT_EXCEEDS_METAL_BALANCE',
  DUPLICATE_INVOICE_NUMBER: 'DUPLICATE_INVOICE_NUMBER',
  INVOICE_NOT_DRAFT: 'INVOICE_NOT_DRAFT',
  CREDIT_NOTE_NOT_VALID: 'CREDIT_NOTE_NOT_VALID',
  ITEM_NOT_SOLD: 'ITEM_NOT_SOLD',
  ITEM_NOT_RETURNED: 'ITEM_NOT_RETURNED',
  BANK_ACCOUNT_REQUIRED: 'BANK_ACCOUNT_REQUIRED',
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  PURCHASE_STOCK_LINE_INCOMPLETE: 'PURCHASE_STOCK_LINE_INCOMPLETE',
  CUSTOMER_SEARCH_QUERY_TOO_SHORT: 'CUSTOMER_SEARCH_QUERY_TOO_SHORT',
  SUPPLIER_SEARCH_QUERY_TOO_SHORT: 'SUPPLIER_SEARCH_QUERY_TOO_SHORT',
  PAYMENT_INVOICE_MISMATCH: 'PAYMENT_INVOICE_MISMATCH',
  SUPPLIER_METAL_PAYMENT_INVALID: 'SUPPLIER_METAL_PAYMENT_INVALID',
  SUPPLIER_PAYMENT_NOTHING_TO_PAY: 'SUPPLIER_PAYMENT_NOTHING_TO_PAY',
  KARIGAR_PAYMENT_NOTHING_TO_PAY: 'KARIGAR_PAYMENT_NOTHING_TO_PAY',
  PHANTOM_RECONCILE_BROKEN: 'PHANTOM_RECONCILE_BROKEN',
  AMOUNT_WORDS_EMPTY: 'AMOUNT_WORDS_EMPTY',
  ESTIMATE_NOT_FOUND: 'ESTIMATE_NOT_FOUND',
  ESTIMATE_EXPIRED: 'ESTIMATE_EXPIRED',
  ESTIMATE_NOT_SAVED: 'ESTIMATE_NOT_SAVED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  FIRM_INVOICE_MISMATCH: 'FIRM_INVOICE_MISMATCH',
  INVOICE_NOT_POSTED: 'INVOICE_NOT_POSTED',
  DEBIT_NOTE_AMOUNT_ZERO: 'DEBIT_NOTE_AMOUNT_ZERO',
  DEBIT_NOTE_REASON_EMPTY: 'DEBIT_NOTE_REASON_EMPTY',
  TAXABLE_AMOUNT_ZERO: 'TAXABLE_AMOUNT_ZERO',

  // --- Phase 3 System Integrity Checks (STEP 19 — Checks 1 to 10) ---
  CHECK_1_INVOICE_NO_LEDGER: 'CHECK_1_INVOICE_NO_LEDGER',
  CHECK_2_MONEY_OUT_STALE_30_DAYS: 'CHECK_2_MONEY_OUT_STALE_30_DAYS',
  CHECK_3_PAYMENT_ORPHAN_PARTY: 'CHECK_3_PAYMENT_ORPHAN_PARTY',
  CHECK_4_OLD_METAL_LOT_NO_RECORD: 'CHECK_4_OLD_METAL_LOT_NO_RECORD',
  CHECK_5_INVOICE_TAMPER: 'CHECK_5_INVOICE_TAMPER',
  CHECK_6_DEBIT_NOTE_BAD_REF: 'CHECK_6_DEBIT_NOTE_BAD_REF',
  CHECK_7_PARTIAL_CN_LOTS: 'CHECK_7_PARTIAL_CN_LOTS',
  CHECK_8_NEGATIVE_PAYABLE_NO_MONEY_OUT: 'CHECK_8_NEGATIVE_PAYABLE_NO_MONEY_OUT',
  CHECK_9_OLD_METAL_CREDIT_MISSING: 'CHECK_9_OLD_METAL_CREDIT_MISSING',
  CHECK_10_KARIGAR_METAL_AGGREGATE: 'CHECK_10_KARIGAR_METAL_AGGREGATE',

  // --- Phase 1 & Phase 2 Scoped Checks ---
  MISSING_SETTINGS: 'MISSING_SETTINGS',
  ITEM_STATUS_INTEGRITY: 'ITEM_STATUS_INTEGRITY',
  STOCK_LOT_WITHOUT_ITEM: 'STOCK_LOT_WITHOUT_ITEM',
  ORPHAN_STOCK_LOT_EVENT: 'ORPHAN_STOCK_LOT_EVENT',
  HUID_FORMAT_VIOLATION: 'HUID_FORMAT_VIOLATION',
  DUPLICATE_HUID: 'DUPLICATE_HUID',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  FY_ID_REQUIRED: 'FY_ID_REQUIRED',
  BANK_ACCOUNT_MUST_BE_NULL_FOR_CASH: 'BANK_ACCOUNT_MUST_BE_NULL_FOR_CASH',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',
  EXCESS_SETTLEMENT_CHOICE_REQUIRED: 'EXCESS_SETTLEMENT_CHOICE_REQUIRED',

  // --- Phase 3 Bank Account Master (Step 16) ---
  BANK_NAME_REQUIRED: 'BANK_NAME_REQUIRED',
  ACCOUNT_HOLDER_REQUIRED: 'ACCOUNT_HOLDER_REQUIRED',
  ACCOUNT_NUMBER_REQUIRED: 'ACCOUNT_NUMBER_REQUIRED',
  IFSC_REQUIRED: 'IFSC_REQUIRED',
  IFSC_INVALID: 'IFSC_INVALID',
  BANK_ACCOUNT_NOT_FOUND: 'BANK_ACCOUNT_NOT_FOUND',
  BANK_ACCOUNT_ALREADY_ARCHIVED: 'BANK_ACCOUNT_ALREADY_ARCHIVED',
  DEFAULT_BANK_ACCOUNT_CANNOT_BE_ARCHIVED: 'DEFAULT_BANK_ACCOUNT_CANNOT_BE_ARCHIVED',

  // --- Phase 3 Transaction Share (Step 20) ---
  INVALID_SHARE_METHOD: 'INVALID_SHARE_METHOD',
  EMAIL_NOT_AVAILABLE: 'EMAIL_NOT_AVAILABLE',
};

export type ErrorCode = (typeof ERR)[keyof typeof ERR];